import Apple from '../../../assets/images/appleLogo.png';
import Tesla from '../../../assets/images/teslaLogo.png';
import Google from '../../../assets/images/googleLogo.png'
import Amazon from '../../../assets/images/amazonLogo.png';
import Netflix from '../../../assets/images/netflixLogo.png';

export const CompanyData = [
    {name: 'Apple', logo: Apple, companyId: 'AAPL'},
    {name: 'Google', logo: Google, companyId: 'GGL'},
    {name: 'Tesla', logo: Tesla, companyId: 'TSLA'},
    {name: 'Nvidia', logo: Tesla, companyId: 'NVDA'},
    {name: 'Oracle', logo: Tesla, companyId: 'ORCL'},
    {name: 'Meta', logo: Tesla, companyId: 'META'},
    {name: 'Netflix', logo: Netflix, companyId: 'NFLX'},
    {name: 'Amazon', logo: Amazon, companyId: 'AMZN'},
    {name: 'Apple', logo: Apple, companyId: 'AAPL'},
    {name: 'Google', logo: Google, companyId: 'GGL'},
    {name: 'Tesla', logo: Tesla, companyId: 'TSLA'},
    {name: 'Nvidia', logo: Tesla, companyId: 'NVDA'},
    {name: 'Oracle', logo: Tesla, companyId: 'ORCL'},
    {name: 'Meta', logo: Tesla, companyId: 'META'},
    {name: 'Netflix', logo: Netflix, companyId: 'NFLX'},
    {name: 'Amazon', logo: Amazon, companyId: 'AMZN'},
    {name: 'Apple', logo: Apple, companyId: 'AAPL'},
    {name: 'Google', logo: Google, companyId: 'GGL'},
    {name: 'Tesla', logo: Tesla, companyId: 'TSLA'},
    {name: 'Nvidia', logo: Tesla, companyId: 'NVDA'},
    {name: 'Oracle', logo: Tesla, companyId: 'ORCL'},
    {name: 'Meta', logo: Tesla, companyId: 'META'},
    {name: 'Netflix', logo: Netflix, companyId: 'NFLX'},
    {name: 'Amazon', logo: Amazon, companyId: 'AMZN'},
    {name: 'Apple', logo: Apple, companyId: 'AAPL'},
    {name: 'Google', logo: Google, companyId: 'GGL'},
    {name: 'Tesla', logo: Tesla, companyId: 'TSLA'},
    {name: 'Nvidia', logo: Tesla, companyId: 'NVDA'},
    {name: 'Oracle', logo: Tesla, companyId: 'ORCL'},
    {name: 'Meta', logo: Tesla, companyId: 'META'},
    {name: 'Netflix', logo: Netflix, companyId: 'NFLX'},
    {name: 'Amazon', logo: Amazon, companyId: 'AMZN'},
    {name: 'Apple', logo: Apple, companyId: 'AAPL'},
    {name: 'Google', logo: Google, companyId: 'GGL'},
    {name: 'Tesla', logo: Tesla, companyId: 'TSLA'},
    {name: 'Nvidia', logo: Tesla, companyId: 'NVDA'},
    {name: 'Oracle', logo: Tesla, companyId: 'ORCL'},
    {name: 'Meta', logo: Tesla, companyId: 'META'},
    {name: 'Netflix', logo: Netflix, companyId: 'NFLX'},
    {name: 'Amazon', logo: Amazon, companyId: 'AMZN'},
    {name: 'Apple', logo: Apple, companyId: 'AAPL'},
    {name: 'Google', logo: Google, companyId: 'GGL'},
    {name: 'Tesla', logo: Tesla, companyId: 'TSLA'},
    {name: 'Nvidia', logo: Tesla, companyId: 'NVDA'},
    {name: 'Oracle', logo: Tesla, companyId: 'ORCL'},
    {name: 'Meta', logo: Tesla, companyId: 'META'},
    {name: 'Netflix', logo: Netflix, companyId: 'NFLX'},
    {name: 'Amazon', logo: Amazon, companyId: 'AMZN'},
]